### ISSUE TITLE
Make jamstats dynamically update when anything changes in-game

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#111]
Currently, jamstats automatically refreshes every X seconds.

Instead, have it dynamically refresh only when there's an actual change to the game state.

Cap the refresh at once every 2 seconds, max, so it's not constantly refreshing.

**Comment by dhmay** [comment]
@bullseye555 , please check out the latest artifact (https://github.com/dhmay/jamstats/actions/runs/4290544430). 

I would guess the behavior isn't 100% ideal, at the moment. If you're just looking at a chart, if the game state updates at all, then the chart will rebuild, even if none of the content has changed. I can try to make that more sophisticated.

But on the whole I think this change is pretty great. It's not any more load on the scoreboard server, it prevents refreshes *unless* something has changed, and you're never more than 2 seconds out of date with the scoreboard.

Let me know what you think, and what the ideal behavior would be.

(I also changed the UI around the info box like you suggested... one thing I'm planning to do is get rid of the empty header space up top and move the displayed chart/table all the way up)

**Comment by dhmay** [comment]
Oh shoot I think I forgot to add a socketio dependency that will make this work... working on that....

**Comment by dhmay** [comment]
OK, should be OK now:
https://github.com/dhmay/jamstats/actions/runs/4290595062

**Comment by dhmay** [comment]
Shoot. I'm still having trouble with that socketio dependency... won't work on Windows yet. When I get it working I'll tag you again.

**Comment by dhmay** [comment]
OK, @bullseye555 , Windows exe is working again. I changed the minimum refresh interval to 3s and made a few UI tweaks.

**Comment by bullseye555** [comment]
Picked up that I started a new game, but then threw an error and wouldn't load anything
![image](https://user-images.githubusercontent.com/28804763/222874518-eb02064a-53aa-4e9a-bab9-3a33a130c619.png)

Also - the message that showed the IP JamStats is running on is no longer there
![image](https://user-images.githubusercontent.com/28804763/222874604-8ffeca95-a9db-403e-970d-f4f88665870a.png)

**Comment by dhmay** [comment]
Arrrrgh, sorry. I'm not sure why you're hitting that code path... maybe because you're starting jamstats before you start your scoreboard? I've been starting the scoreboard first. Anyway, I fixed that specific bug, hope that's the only bug.

Not sure about the IP message thing... you mean you're not seeing that any more?

**Comment by bullseye555** [comment]
IP Message: Left is the last working instance I have 
![image](https://user-images.githubusercontent.com/28804763/222877323-115f48e4-3bf8-4c86-b0b9-5d9a015f6d11.png)

also, after the update from pull 311, JS isn't even loading in web browser - I just get the spinning-circle-of-death

![image](https://user-images.githubusercontent.com/28804763/222877404-dd35ca5c-4b80-4880-bbd0-901899b566b6.png)

There doesn't appear to be any action, either - time of screenshot is 16:18, last logged time 16:13
![image](https://user-images.githubusercontent.com/28804763/222877426-bb242344-1b5f-4bec-ac4f-26de7ba9f222.png)

**Comment by dhmay** [comment]
Dang I sure hope that’s all because of the bug I fixed!
________________________________

**Comment by dhmay** [comment]
@bullseye555, in the last several days I've implemented a new page aimed at announcers:

The "Current Skaters" table shows who's currently skating, with position for each skater and attributes of jammers (lead, lost, on initial pass) and pivots (StarPass). I'm hoping to test this out on Sunday at an F&F game in our league, but if you have a chance to check it out before then, I'd love any feedback you've got!

I'm particularly interested in the jammer attributes... do they appear to be correct? I.e., when a jam starts, do both jammers have "J (on init)" for their position, and does that go away when each jammer completes initial? 

Let me know what you think of this thing... I'm hoping this is exactly the info that announcers want, but I can add, change, rearrange.

**Comment by dhmay** [comment]
The interface:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/714077/224465947-eb15df08-eb8e-4d2d-8895-5387cfdd8b09.png">

**Comment by bullseye555** [comment]
Using push #330 - I'm still not able to load JamStats WebUI

![image](https://user-images.githubusercontent.com/28804763/224483606-222df2d2-1d49-4766-9f76-ddab50d52445.png)
Time of screenshot was 11:09:?? so should have refreshed at least twice, but nothing has updated in the debug window to show it's done anything

**Comment by dhmay** [comment]
Oh! Shoot. Can you please try checking the debug checkbox? That'll help me get a better idea of where it's hitting a problem, I think.

**Comment by dhmay** [comment]
Ah, ok, I think the webserver isn't starting, and it's hanging forever, trying. It happens with the Windows executable, but not with my Python environment on my Mac. 

That's going to be really hard for me to debug, but at least I can reproduce it with a Windows box in the house. I'll ping again when I think I've got it fixed.

**Comment by dhmay** [comment]
OK, @bullseye555, I don't understand *why* this seems to work, but it does, on my Windows box:

Instead of double-clicking jamstats.exe or running it from the commandline with no arguments, instead go to the command prompt, change to the directory where jamstats.exe is, and type:

.\jamstats.exe --scoreboardserver=<server:port> --jamstatsport=8000

Then the output (including the URL to use to connect to jamstats) will appear in the terminal window.

Let me know if that works! I'll keep working on restoring the web UI for entering arguments... it makes no sense to me that that's the problem.

**Comment by dhmay** [comment]
@erevrav  fyi

**Comment by dhmay** [comment]
Yep, the problem is *entirely* with the GUI argument-capture interface. Nothing to do with the jamstats webserver stuff, at all. Everything should work fine from the commandline, nothing works from the GUI.

**Comment by dhmay** [comment]
OK, I got it! @bullseye555 , please grab the latest build from Actions. 

I tested on my Windows laptop, running against a live scoreboard, using the GUI to enter arguments. Everything's fine here. 

If you still run into problems with the latest build (I don't think you will!), please try the commandline approach I suggested above, adding the "--debug" flag, and dump the output here.

**Comment by bullseye555** [comment]
[PUSH338 - GUI Log (no debug).txt](https://github.com/dhmay/jamstats/files/10949803/PUSH338.-.GUI.Log.no.debug.txt)
[PUSH338 - CMD Log.txt](https://github.com/dhmay/jamstats/files/10949804/PUSH338.-.CMD.Log.txt)
[PUSH341 - GUI Log (debug).txt](https://github.com/dhmay/jamstats/files/10949805/PUSH341.-.GUI.Log.debug.txt)

Sorry @dhmay :( Windows 11 throwing a hissyfit, and I even dug out an older PC that has Win10 on it and no dice

I tried push 338, 341 and 343 commits, all with no luck

Logs attached above

**Comment by dhmay** [comment]
What kind of hissyfit is it thowing? I think commit #347 might fix it.

**Comment by dhmay** [comment]
@bullseye555 I would be reluctant to ask you to try *yet another* version, but @erevrav  was also getting hissyfit issues, and I think we worked through them _**all**_ in #347.

**Comment by bullseye555** [comment]
All good, @dhmay ! It's what I'm here for 😄 
the "Hissyfit" was just WebUI not loading

I'll have a look at 347 now

**Comment by bullseye555** [comment]
**hailermaryer** (I literally laughed at that) worked 😃 
![image](https://user-images.githubusercontent.com/28804763/224520884-d3cdf19f-dc45-4533-ad0a-7f35acf71480.png)

But the _Current Skaters_ is showing 2 Jammers for each team - neither of which are the actual jammer... 
![image](https://user-images.githubusercontent.com/28804763/224520943-aff23bb8-efa9-4d86-b12d-f5c244b92adb.png)

And when I add all 4 skating positions, it has 5 jammers 
![image](https://user-images.githubusercontent.com/28804763/224520996-d16bd339-8758-4c3b-8e60-e90ae9d0bc6d.png)
![image](https://user-images.githubusercontent.com/28804763/224521005-424cb4ab-b985-4bd7-aff5-fabbadf44546.png)
(Changing the Pivot to a different number doesn't change the Jammer, either)
![image](https://user-images.githubusercontent.com/28804763/224521008-09393ce1-91db-47a4-b626-a83cb8ae3bdb.png)

I also confirmed that having **only** the jammer doesn't make a difference - it's still showing skater number 6 as the jammer for both teams

**Comment by dhmay** [comment]
A lot of those issues, I think, are because your players all have the same player name. :)

I should probably be joining on player number, but I'm using player name. With real data, I think it's behaving pretty well.

**Comment by bullseye555** [comment]
Ah-ha

I'm about to head out for the rest of the day, so will give it a go with Named skaters tomorrow

**Comment by dhmay** [comment]
One thing you will notice, I think, is that it can't tell you anything about the lineup *before* a jam starts. I'll try to work on that, but it'll probably take me a while.

**Comment by bullseye555** [comment]
Confirming it's all good when I have a game with skater names... but yeah, might be worthwhile joining on numbers - there can be scenarios where a skaters name isn't populated (albeit an edge case, but it does happen)
![image](https://user-images.githubusercontent.com/28804763/224543951-d1ad9a96-9019-4b5a-b723-b973203dec99.png)

I also had another issue getting it to load... The push 347 asset loaded without issue earlier today, but then tonight when trying to test with skater names, it failed to load on both my Win10 and Win11 device, but had no issues on the WinServer19 device that's running the scoreboard.... so IDK what's happening 😕

**Comment by dhmay** [comment]
Weird! What did "failed to load" mean, exactly?

**Comment by bullseye555** [comment]
WebUI just... doesn't load. Same issue as originally commented in this thread

https://github.com/dhmay/jamstats/issues/111#issuecomment-1454461029
![image](https://user-images.githubusercontent.com/28804763/224585597-4a79be2e-db4d-4d46-96fa-2f60c451985f.png)

**Comment by dhmay** [comment]
Argh. OK, I'm going to close this issue as completed (since it is, when it works at all) and open a separate issue for it not working on... I guess, some versions of Windows.
